"""added category

Revision ID: 04475abbbae5
Revises: 54ad8b86fc16
Create Date: 2021-03-19 21:08:13.690013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04475abbbae5'
down_revision = '54ad8b86fc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_data', sa.Column('category', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_data', 'category')
    # ### end Alembic commands ###
