"""netflix view history

Revision ID: 12ac4514fc2b
Revises: 04475abbbae5
Create Date: 2021-03-21 18:34:24.731309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ac4514fc2b'
down_revision = '04475abbbae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netflix_view_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta', sa.String(length=100), nullable=True),
    sa.Column('perfil', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('temporada', sa.String(length=255), nullable=True),
    sa.Column('episodio', sa.String(length=255), nullable=True),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('netflix_view_history')
    # ### end Alembic commands ###
