"""imdbmovies

Revision ID: 1985083a926c
Revises: 476869b2600e
Create Date: 2021-04-20 18:26:24.401817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1985083a926c'
down_revision = '476869b2600e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imdb_movies',
    sa.Column('codigo_imdb', sa.String(length=20), nullable=False),
    sa.Column('titulo_filme', sa.String(length=200), nullable=True),
    sa.Column('titulo_filme_original', sa.String(length=200), nullable=True),
    sa.Column('ano_lancamento', sa.Integer(), nullable=True),
    sa.Column('data_lancamento', sa.DateTime(), nullable=True),
    sa.Column('genero', sa.String(length=200), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('pais', sa.String(length=200), nullable=True),
    sa.Column('lingua', sa.String(length=200), nullable=True),
    sa.Column('diretor', sa.String(length=200), nullable=True),
    sa.Column('escritor', sa.String(length=200), nullable=True),
    sa.Column('empresa_produtora', sa.String(length=200), nullable=True),
    sa.Column('atores', sa.String(length=1000), nullable=True),
    sa.Column('descricao', sa.String(length=1200), nullable=True),
    sa.Column('media_votos', sa.Float(), nullable=True),
    sa.Column('quantidade_votos', sa.Float(), nullable=True),
    sa.Column('custo_producao', sa.String(length=200), nullable=True),
    sa.Column('eua_lucro_bruto', sa.String(length=200), nullable=True),
    sa.Column('lucro_bruto', sa.String(length=200), nullable=True),
    sa.Column('metascore', sa.Float(), nullable=True),
    sa.Column('qtde_notas_usuarios', sa.Float(), nullable=True),
    sa.Column('qtde_notas_criticos', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('codigo_imdb')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imdb_movies')
    # ### end Alembic commands ###
