"""quadrante change2

Revision ID: 3a9634f7a778
Revises: 608425f9feb9
Create Date: 2021-03-16 08:23:48.320854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9634f7a778'
down_revision = '608425f9feb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quadrante', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quadrante', 'id')
    # ### end Alembic commands ###
