"""nextflix

Revision ID: 40544db61e1e
Revises: a3cb0677fa40
Create Date: 2021-03-15 19:25:25.981093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40544db61e1e'
down_revision = 'a3cb0677fa40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netflix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('diretor', sa.String(length=255), nullable=True),
    sa.Column('elenco', sa.String(length=4000), nullable=True),
    sa.Column('pais', sa.String(length=255), nullable=True),
    sa.Column('data_lancamento', sa.DateTime(), nullable=True),
    sa.Column('ano_lancamento', sa.Integer(), nullable=True),
    sa.Column('censura', sa.String(length=255), nullable=True),
    sa.Column('duracao', sa.String(length=255), nullable=True),
    sa.Column('listado', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('netflix')
    # ### end Alembic commands ###
