"""venda livros

Revision ID: 476869b2600e
Revises: ed5eb83c2f95
Create Date: 2021-04-19 08:31:42.121753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476869b2600e'
down_revision = 'ed5eb83c2f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venda_livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('genero', sa.String(length=200), nullable=True),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda_livros')
    # ### end Alembic commands ###
