"""survey data

Revision ID: 54ad8b86fc16
Revises: 3a9634f7a778
Create Date: 2021-03-17 12:20:22.028183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ad8b86fc16'
down_revision = '3a9634f7a778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respondent', sa.String(length=100), nullable=True),
    sa.Column('question', sa.String(length=4000), nullable=True),
    sa.Column('answer', sa.String(length=4000), nullable=True),
    sa.Column('application', sa.String(length=100), nullable=True),
    sa.Column('survey_name', sa.String(length=100), nullable=True),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_data')
    # ### end Alembic commands ###
