"""quadrante change

Revision ID: 608425f9feb9
Revises: 0008e53ae50b
Create Date: 2021-03-16 08:21:15.540607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608425f9feb9'
down_revision = '0008e53ae50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quadrante', sa.Column('topico', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quadrante', 'topico')
    # ### end Alembic commands ###
