"""artigos

Revision ID: 88c4a58d0477
Revises: 12ac4514fc2b
Create Date: 2021-03-31 19:21:32.777342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c4a58d0477'
down_revision = '12ac4514fc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=400), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artigos')
    # ### end Alembic commands ###
