"""start

Revision ID: 919d1d8af883
Revises: 
Create Date: 2021-03-07 18:28:20.871365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919d1d8af883'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imdb_movies',
    sa.Column('imdb_title_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('date_published', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('writer', sa.String(length=255), nullable=True),
    sa.Column('production_company', sa.String(length=255), nullable=True),
    sa.Column('actors', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avg_vote', sa.Float(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('usa_gross_income', sa.Float(), nullable=True),
    sa.Column('worlwide_gross_income', sa.Float(), nullable=True),
    sa.Column('metascore', sa.Float(), nullable=True),
    sa.Column('reviews_from_users', sa.Float(), nullable=True),
    sa.Column('reviews_from_critics', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('imdb_title_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imdb_movies')
    # ### end Alembic commands ###
