"""start

Revision ID: a3cb0677fa40
Revises: 
Create Date: 2021-03-13 19:35:00.983616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cb0677fa40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brasileirao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rodada', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('horario', sa.String(length=255), nullable=True),
    sa.Column('dia', sa.String(length=255), nullable=True),
    sa.Column('mandante', sa.String(length=255), nullable=True),
    sa.Column('visitante', sa.String(length=255), nullable=True),
    sa.Column('vencedor', sa.String(length=255), nullable=True),
    sa.Column('arena', sa.String(length=255), nullable=True),
    sa.Column('placar_mandante', sa.Integer(), nullable=True),
    sa.Column('placar_visitante', sa.Integer(), nullable=True),
    sa.Column('estado_mandante', sa.String(length=255), nullable=True),
    sa.Column('estado_visitante', sa.String(length=255), nullable=True),
    sa.Column('estado_vencedor', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brasileirao_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rodada', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('horario', sa.String(length=255), nullable=True),
    sa.Column('dia', sa.String(length=255), nullable=True),
    sa.Column('visitante', sa.String(length=255), nullable=True),
    sa.Column('vencedor', sa.String(length=255), nullable=True),
    sa.Column('arena', sa.String(length=255), nullable=True),
    sa.Column('placar_mandante', sa.Integer(), nullable=True),
    sa.Column('placar_visitante', sa.Integer(), nullable=True),
    sa.Column('estado_mandante', sa.String(length=255), nullable=True),
    sa.Column('estado_visitante', sa.String(length=255), nullable=True),
    sa.Column('estado_vencedor', sa.String(length=255), nullable=True),
    sa.Column('mandante', sa.Integer(), nullable=False),
    sa.Column('chutes', sa.Integer(), nullable=True),
    sa.Column('chutes_gol', sa.Integer(), nullable=True),
    sa.Column('posse_bola', sa.Float(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('precisao_passe', sa.Float(), nullable=True),
    sa.Column('faltas', sa.Integer(), nullable=True),
    sa.Column('cartoes_amarelos', sa.Integer(), nullable=True),
    sa.Column('cartoes_vermelhos', sa.Integer(), nullable=True),
    sa.Column('impedimentos', sa.Integer(), nullable=True),
    sa.Column('escanteios', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'mandante')
    )
    op.create_table('filmes_brasil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano_exibicao', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('genero', sa.String(length=100), nullable=True),
    sa.Column('pais_produtor', sa.String(length=255), nullable=True),
    sa.Column('nacionalidade', sa.String(length=255), nullable=True),
    sa.Column('empresa_distribuidora', sa.String(length=255), nullable=True),
    sa.Column('origem_empresa_distribuidora', sa.String(length=255), nullable=True),
    sa.Column('publico_ano_exibicao', sa.Integer(), nullable=True),
    sa.Column('renda_ano_exibicao', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmes_brasil')
    op.drop_table('brasileirao_stats')
    op.drop_table('brasileirao')
    # ### end Alembic commands ###
