"""change field

Revision ID: ac8c0352a6e5
Revises: 1985083a926c
Create Date: 2021-04-20 18:30:22.317299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8c0352a6e5'
down_revision = '1985083a926c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
