"""combustivel

Revision ID: ed5eb83c2f95
Revises: 88c4a58d0477
Create Date: 2021-04-15 15:02:51.426764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5eb83c2f95'
down_revision = '88c4a58d0477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combustivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('percorrida', sa.Float(), nullable=True),
    sa.Column('alcool', sa.Float(), nullable=True),
    sa.Column('gasolina', sa.Float(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('litros', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combustivel')
    # ### end Alembic commands ###
